# This is my personal workflow that executes in my lab environment. Feel free to use this as a base should you want to do something similar.

name: Template Create

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-2022GUI:
    runs-on: windows-packer
    steps:
    - uses: actions/checkout@v2
    - name: Build  GUI template
      env:
        build_account: ${{ secrets.PKR_VCA_SVC_ACCT }}
        build_pw: ${{ secrets.PKR_VCA_SVC_ACCT_PW }}
        cluster: ${{ secrets.PKR_HOST_CLUSTER }}
        vcsa: ${{ secrets.PKR_VCA }}
        datacenter: ${{ secrets.PKR_VCA_DC }}
        datastore: ${{ secrets.PKR_DATASTORE }}
        network: ${{ secrets.PKR_VNET }}
        iso: ${{ secrets.PKR_ISO_PATH }}
      run: >
        packer build -force 
        -var 'vsphere-user="${{ env.build_account }}"' 
        -var 'vsphere-password="${{ env.build_pw }}"' 
        -var 'vsphere-server="${{ env.vcsa }}"' 
        -var 'vsphere-cluster="${{ env.cluster }}"' 
        -var 'vsphere-datacenter="${{ env.datacenter }}"' 
        -var 'vsphere-datastore="${{ env.datastore }}"' 
        -var 'vsphere-network="${{ env.network }}"' 
        -var 'os_iso_path="${{ env.iso }}"' 
        .\win10.vdi\
      # The above run call makes heavy use of masked secrets held in GitHub Actions. Substitute for your own variables or secrets